### ISSUE TITLE
1.20.5 support

### ISSUE THREAD

**Issue by bauerbach** [haselkern/Minecraft-ArmorStand#49]
Mojang changed how entity data tags work in 1.20.5, meaning the /give commands provided by this tool no longer work. Can you please add support for 1.20.5?

**Comment by Hashir103** [comment]
In 1.20.5+ the EntityTag property given on the site needs to be updated to the new component tags which would mean requiring the item/entity ID now in the data as well and changing the syntax.

<ins>1.16-1.20.4 Give Command (found on the site)</ins>

`/give @p armor_stand{EntityTag:{Invulnerable:1b,NoBasePlate:1b}} 1`

<ins>1.20.5+ Give Command</ins>

`/give @p armor_stand[entity_data={id:"armor_stand",Invulnerable:1b,NoBasePlate:1b}]`

***

It is worth noting that even though both Summon/Give will work with this change, there are other issues with the armor stands such as player heads, leather colour etc. All of these properties need to be modified to comply with the component tag syntax. Check the [1.20.5 Patch notes](https://www.minecraft.net/en-us/article/minecraft-java-edition-1-20-5) to see every change made if someone has the time for a comprehensive update.

For example, player heads:

<ins>1.16-1.20.4 Give Command (found on the site)</ins>

`/give @p armor_stand{EntityTag:{Invulnerable:1b,NoBasePlate:1b,NoGravity:1b,ShowArms:1b,ArmorItems:[{},{},{},{id:"player_head",Count:1b,tag:{SkullOwner:"Hash1r"}}],HandItems:[{},{}],Pose:{LeftLeg:[265f,0f,0f],RightLeg:[264f,0f,0f],LeftArm:[310f,0f,0f],RightArm:[307f,0f,0f]}}}`

<ins>1.20.5+ Give Command</ins>

`/give @p armor_stand[entity_data={id:"armor_stand",Invulnerable:1b,NoBasePlate:1b,NoGravity:1b,ShowArms:1b,ArmorItems:[{},{},{},{id:"player_head",Count:1b,components:{profile:{name:"Hash1r"}}}],HandItems:[{},{}],Pose:{LeftLeg:[265f,0f,0f],RightLeg:[264f,0f,0f],LeftArm:[310f,0f,0f],RightArm:[307f,0f,0f]}}]`

**Comment by BerryCutePixels** [comment]
For anyone else looking in the future here's the new updated code if you want to use armor stands for invisible text, just replace "armor_stand" after custom_name with whatever you want
(remove Marker:1b if you want the text to float above the armor stand instead of being positioned under it)

`/give @p armor_stand[entity_data={id:"armor_stand",Invisible:1b,Invulnerable:1b,NoBasePlate:1b,CustomNameVisible:1b,PersistenceRequired:1b,NoGravity:1b,Marker:1b},custom_name=armor_stand]`
